// ledgerSchema.js
// Single source of truth for the BIAN v14 Ledger MVP data model.
// Consumed by:
//   - DocumentSnippet (inline alias tooltips per field)
//   - CollectionDrawer (full collection schema browser)
//
// Future: swap the literal JSON for a fetch from /api/bian/ledger-schema.
// The shape MUST match — `aliasMap()` is the contract used by the UI.

export const META = {
  version: "v1.0-MVP",
  title: "BIAN v14 Ledger & Sub-Ledger Data Model — MongoDB MVP",
  database: "leafy_bank_bian",
  bianServiceDomain: "FinancialAccounting",
  bianControlRecord: "FinancialBookingLog",
  bianBQ: "LedgerPosting",
  bianPattern: "Management",
  bianVersion: "v14",
};

// Each collection: description, BIAN classification, fields (with BIAN alias +
// description + required), indexes, sample document. The shape mirrors the
// canonical data-model JSON exactly so a future fetch swap is trivial.
export const COLLECTIONS = {
  glAccounts: {
    mongoAlias: "glAccounts",
    description:
      "Chart of Accounts — master registry of all GL account codes. One document per account. Referenced by all journal and sub-ledger entries.",
    immutable: false,
    bianClassification: {
      sd: "FinancialAccounting",
      cr: "FinancialBookingLog",
      bq: "LedgerPosting",
      pattern: "Management",
    },
    fields: [
      { name: "_id", type: "objectId", required: true, bian: "FinancialAccountReference", note: "MongoDB PK" },
      { name: "accountCode", type: "string", required: true, bian: "FinancialAccountCode", note: "Unique code e.g. 1001, 2100, 4000. Indexed unique." },
      { name: "accountName", type: "string", required: true, bian: "FinancialAccountName", note: "e.g. Cash and Cash Equivalents" },
      { name: "accountType", type: "string", required: true, bian: "FinancialAccountType", note: "ASSET | LIABILITY | EQUITY | INCOME | EXPENSE" },
      { name: "normalBalance", type: "string", required: true, bian: "FinancialAccountNormalBalanceType", note: "DEBIT | CREDIT — the side that increases the account" },
      { name: "parentAccountCode", type: "string", required: false, bian: "ParentAccountReference", note: "Sparse — FK to parent glAccounts.accountCode for hierarchy" },
      { name: "level", type: "int", required: true, bian: "AccountHierarchyLevel", note: "1=category, 2=group, 3=control, 4=detail. Posting only at level 4." },
      { name: "isPostingAccount", type: "bool", required: true, bian: "FinancialAccountPostingIndicator", note: "Only level-4 accounts accept journal entries" },
      { name: "currency", type: "string", required: true, bian: "FinancialAccountCurrencyCode", note: "ISO 4217 — functional currency of the account" },
      { name: "subLedgerType", type: "string", required: false, bian: "SubLedgerTypeCode", note: "Sparse. ACCOUNTS_RECEIVABLE | ACCOUNTS_PAYABLE | FIXED_ASSETS | CUSTOMER_DEPOSITS | LOAN_PORTFOLIO | null (pure GL)" },
      { name: "status", type: "string", required: true, bian: "FinancialAccountStatusType", note: "ACTIVE | INACTIVE | FROZEN" },
      { name: "description", type: "string", required: false, bian: "FinancialAccountDescriptionText", note: "Narrative description of account purpose" },
      { name: "createdAt", type: "date", required: true },
      { name: "updatedAt", type: "date", required: true },
    ],
    indexes: [
      { name: "idx_account_code_unique", key: "{ accountCode: 1 }", unique: true },
      { name: "idx_account_type", key: "{ accountType: 1 }" },
      { name: "idx_subledger_type", key: "{ subLedgerType: 1 }", sparse: true },
      { name: "idx_parent_account", key: "{ parentAccountCode: 1 }", sparse: true },
    ],
    sampleDocument: {
      accountCode: "1001",
      accountName: "Cash and Cash Equivalents",
      accountType: "ASSET",
      normalBalance: "DEBIT",
      parentAccountCode: "1000",
      level: 4,
      isPostingAccount: true,
      currency: "USD",
      subLedgerType: null,
      status: "ACTIVE",
      description: "Nostro and operational cash accounts",
      createdAt: { $date: "2026-01-01T00:00:00Z" },
      updatedAt: { $date: "2026-01-01T00:00:00Z" },
    },
    designDecisionIds: [9, 10],
  },

  journalEntries: {
    mongoAlias: "journalEntries",
    description:
      "General Ledger journal entries — double-entry bookkeeping. IMMUTABLE once status=POSTED. Reversals create new documents; originals are never modified. Each document is one complete balanced journal (sum of debits = sum of credits).",
    immutable: true,
    bianClassification: {
      sd: "FinancialAccounting",
      cr: "FinancialBookingLog",
      bq: "LedgerPosting",
      pattern: "Management",
    },
    fields: [
      { name: "_id", type: "objectId", required: true, bian: "FinancialBookingLogReference" },
      { name: "journalId", type: "string", required: true, bian: "FinancialBookingLogIdentifier", note: "Business key. Format: JNL-YYYYMMDD-{seq} e.g. JNL-20260415-000042" },
      { name: "idempotencyKey", type: "string", required: true, bian: "FinancialBookingLogIdempotencyKey", note: "CRITICAL. Client-generated UUID. Unique index prevents duplicate postings on retry. Include in every POST request." },
      { name: "periodCode", type: "string", required: true, bian: "FinancialBookingLogPeriodCode", note: "Accounting period code. Format: YYYY-MM e.g. \"2026-04\"." },
      { name: "periodName", type: "string", required: true, bian: "FinancialBookingLogPeriodName", note: "Human-readable period name e.g. \"April 2026\". Denormalized companion to periodCode." },
      { name: "valueDate", type: "date", required: true, bian: "FinancialBookingLogValueDate", note: "Economic date of the transaction (may differ from postingDate)" },
      { name: "postingDate", type: "date", required: true, bian: "FinancialBookingLogPostingDateTime", note: "System date when entry was posted — set by server" },
      { name: "journalType", type: "string", required: true, bian: "FinancialBookingLogType", note: "MANUAL | SYSTEM | REVERSAL | ADJUSTMENT | SUBLEDGER_TRANSFER | PERIOD_CLOSE" },
      { name: "status", type: "string", required: true, bian: "FinancialBookingLogLifecycleStatusType", note: "DRAFT | PENDING_APPROVAL | POSTED | REJECTED | REVERSED" },
      { name: "currency", type: "string", required: true, bian: "FinancialBookingLogCurrencyCode", note: "ISO 4217 functional currency" },
      { name: "totalAmount", type: "decimal", required: true, bian: "FinancialBookingLogTotalAmount", note: "Sum of all debit entries. Must equal sum of all credits. Use Decimal128." },
      { name: "description", type: "string", required: true, bian: "FinancialBookingLogDescriptionText", note: "Narrative description of the business event" },
      { name: "sourceReference", type: "object", required: true, bian: "FinancialBookingLogSourceReference", note: "Traceability to originating event — { sourceSystem, sourceId, sourceType, sourceCollection }" },
      { name: "entries", type: "array", required: true, bian: "LedgerPostingRecord", note: "Array of debit/credit lines. Min 2. Must balance." },
      { name: "reversalOf", type: "string", required: false, bian: "FinancialBookingLogReversalOfReference", note: "Sparse. journalId of the original entry this reverses." },
      { name: "reversedBy", type: "string", required: false, bian: "FinancialBookingLogReversedByReference", note: "Sparse. journalId of the reversal entry." },
      { name: "approvedBy", type: "string", required: false, bian: "FinancialBookingLogApprovedByReference" },
      { name: "approvedAt", type: "date", required: false, bian: "FinancialBookingLogApprovalDateTime" },
      { name: "postedBy", type: "string", required: false, bian: "FinancialBookingLogPostedByReference" },
      { name: "createdAt", type: "date", required: true },
      { name: "updatedAt", type: "date", required: true },
    ],
    entryFields: [
      { name: "lineNumber", type: "int", bian: "LedgerPostingSequenceNumber" },
      { name: "accountCode", type: "string", bian: "LedgerPostingFinancialAccountCode", note: "FK → glAccounts.accountCode. Must be isPostingAccount=true" },
      { name: "accountName", type: "string", bian: "LedgerPostingFinancialAccountName", note: "Denormalized for read performance" },
      { name: "side", type: "string", bian: "LedgerPostingDebitCreditType", note: "DEBIT | CREDIT" },
      { name: "amount", type: "decimal", bian: "LedgerPostingTransactionAmount", note: "Decimal128 — always positive. Sign conveyed by 'side'." },
      { name: "currency", type: "string", bian: "LedgerPostingCurrencyCode", note: "ISO 4217" },
      { name: "fxRate", type: "decimal", bian: "LedgerPostingFXRate", note: "Sparse. FX conversion rate if currency differs from functional" },
      { name: "functionalAmount", type: "decimal", bian: "LedgerPostingFunctionalAmount" },
      { name: "subLedgerRef", type: "string", bian: "LedgerPostingSubLedgerReference", note: "Sparse FK → subLedgerEntries._id" },
      { name: "costCenter", type: "string", bian: "LedgerPostingCostCenterReference" },
      { name: "lineDescription", type: "string", bian: "LedgerPostingDescriptionText" },
    ],
    indexes: [
      { name: "idx_journal_id_unique", key: "{ journalId: 1 }", unique: true },
      { name: "idx_idempotency_key_unique", key: "{ idempotencyKey: 1 }", unique: true },
      { name: "idx_period_status", key: "{ periodCode: 1, status: 1 }" },
      { name: "idx_value_date", key: "{ valueDate: -1 }" },
      { name: "idx_source_id", key: "{ 'sourceReference.sourceId': 1 }" },
      { name: "idx_source_system_type", key: "{ 'sourceReference.sourceSystem': 1, 'sourceReference.sourceType': 1 }" },
      { name: "idx_status_posting_date", key: "{ status: 1, postingDate: -1 }" },
    ],
    sampleDocument: {
      journalId: "JNL-20260415-000042",
      idempotencyKey: "pay-550e8400-e29b-41d4-a716-446655440000",
      periodCode: "2026-04",
      periodName: "April 2026",
      valueDate: { $date: "2026-04-15T00:00:00Z" },
      postingDate: { $date: "2026-04-15T10:23:45Z" },
      journalType: "SYSTEM",
      status: "POSTED",
      currency: "USD",
      totalAmount: { $numberDecimal: "1000.00" },
      description: "Customer payment received — SWIFT MT103 ref TXN-EA2AEEDA",
      sourceReference: {
        sourceSystem: "PAYMENT_ORDER",
        sourceId: "PAY-20260415-0042",
        sourceType: "PAYMENT",
        sourceCollection: "payments",
      },
      entries: [
        {
          lineNumber: 1,
          accountCode: "1001",
          accountName: "Cash and Cash Equivalents",
          side: "DEBIT",
          amount: { $numberDecimal: "1000.00" },
          currency: "USD",
          fxRate: null,
          functionalAmount: { $numberDecimal: "1000.00" },
          subLedgerRef: null,
          costCenter: "RETAIL-BANKING",
          lineDescription: "Cash in from customer payment",
        },
        {
          lineNumber: 2,
          accountCode: "2100",
          accountName: "Customer Deposits — Current",
          side: "CREDIT",
          amount: { $numberDecimal: "1000.00" },
          currency: "USD",
          fxRate: null,
          functionalAmount: { $numberDecimal: "1000.00" },
          subLedgerRef: "SL-20260415-000042",
          costCenter: "RETAIL-BANKING",
          lineDescription: "Customer deposit credit — account ACC-001234",
        },
      ],
    },
    designDecisionIds: [1, 2, 3, 5, 7, 11],
  },

  subLedgerEntries: {
    mongoAlias: "subLedgerEntries",
    description:
      "Sub-ledger entries — detailed transaction records linked to a GL control account. Provides the granular business context behind each GL posting. Balances here must reconcile to the corresponding GL control account balance. IMMUTABLE once status=POSTED.",
    immutable: true,
    bianClassification: {
      sd: "FinancialAccounting",
      cr: "FinancialBookingLog",
      bq: "LedgerPosting",
      pattern: "Management",
    },
    fields: [
      { name: "_id", type: "objectId", required: true, bian: "LedgerPostingReference" },
      { name: "subLedgerId", type: "string", required: true, bian: "LedgerPostingIdentifier", note: "Business key. Format: SL-YYYYMMDD-{seq}" },
      { name: "idempotencyKey", type: "string", required: true, bian: "LedgerPostingIdempotencyKey", note: "Same key as parent journalEntries — prevents duplicate postings on retry." },
      { name: "journalEntryId", type: "string", required: true, bian: "LedgerPostingFinancialBookingLogReference", note: "FK → journalEntries.journalId. Parent GL posting." },
      { name: "periodCode", type: "string", required: true, bian: "FinancialBookingLogPeriodCode", note: "Must match parent journalEntries.periodCode." },
      { name: "periodName", type: "string", required: true, note: "Must match parent journalEntries.periodName." },
      { name: "subLedgerType", type: "string", required: true, bian: "LedgerPostingSubLedgerTypeCode", note: "ACCOUNTS_RECEIVABLE | ACCOUNTS_PAYABLE | CUSTOMER_DEPOSITS | LOAN_PORTFOLIO | FIXED_ASSETS | INTER_BANK" },
      { name: "controlAccountCode", type: "string", required: true, bian: "LedgerPostingFinancialAccountCode", note: "FK → glAccounts.accountCode (the parent GL control account this sub-ledger rolls up to)" },
      { name: "entityReference", type: "object", required: true, bian: "LedgerPostingEntityReference", note: "{ entityType, entityId, entityName }" },
      { name: "side", type: "string", required: true, bian: "LedgerPostingDebitCreditType", note: "DEBIT | CREDIT" },
      { name: "amount", type: "decimal", required: true, bian: "LedgerPostingTransactionAmount", note: "Decimal128 — always positive" },
      { name: "currency", type: "string", required: true, bian: "LedgerPostingCurrencyCode" },
      { name: "functionalAmount", type: "decimal", required: true, bian: "LedgerPostingFunctionalAmount" },
      { name: "runningBalance", type: "decimal", required: false, bian: "LedgerPostingRunningBalance", note: "Optional — running balance per entity for this sub-ledger type. O(1) balance lookup per entity." },
      { name: "valueDate", type: "date", required: true, bian: "LedgerPostingValueDate" },
      { name: "postingDate", type: "date", required: true, bian: "LedgerPostingPostingDateTime" },
      { name: "transactionType", type: "string", required: true, bian: "LedgerPostingTransactionType", note: "PAYMENT_IN | PAYMENT_OUT | LOAN_DISBURSEMENT | LOAN_REPAYMENT | INTEREST_CHARGE | FEE | DEPOSIT | WITHDRAWAL | ADJUSTMENT" },
      { name: "status", type: "string", required: true, bian: "LedgerPostingLifecycleStatusType", note: "POSTED | REVERSED" },
      { name: "sourceReference", type: "object", required: true, bian: "LedgerPostingSourceReference", note: "Same structure as journalEntries.sourceReference" },
      { name: "description", type: "string", required: true, bian: "LedgerPostingDescriptionText" },
      { name: "reversalOf", type: "string", required: false, bian: "LedgerPostingReversalOfReference", note: "Sparse — supports immutable ledger reversal." },
      { name: "reversedBy", type: "string", required: false, bian: "LedgerPostingReversedByReference" },
      { name: "createdAt", type: "date", required: true },
      { name: "updatedAt", type: "date", required: true },
    ],
    indexes: [
      { name: "idx_subledger_id_unique", key: "{ subLedgerId: 1 }", unique: true },
      { name: "idx_idempotency_key_unique", key: "{ idempotencyKey: 1 }", unique: true },
      { name: "idx_journal_entry_id", key: "{ journalEntryId: 1 }" },
      { name: "idx_entity_date", key: "{ 'entityReference.entityId': 1, valueDate: -1 }" },
      { name: "idx_subledger_type_period", key: "{ subLedgerType: 1, periodCode: 1 }" },
      { name: "idx_control_account_date", key: "{ controlAccountCode: 1, valueDate: -1 }" },
      { name: "idx_entity_status", key: "{ 'entityReference.entityType': 1, 'entityReference.entityId': 1, status: 1 }" },
    ],
    sampleDocument: {
      subLedgerId: "SL-20260415-000042",
      idempotencyKey: "pay-550e8400-e29b-41d4-a716-446655440000",
      journalEntryId: "JNL-20260415-000042",
      periodCode: "2026-04",
      periodName: "April 2026",
      subLedgerType: "CUSTOMER_DEPOSITS",
      controlAccountCode: "2100",
      entityReference: {
        entityType: "ACCOUNT",
        entityId: "ACC-001234",
        entityName: "Jane Smith — Current Account",
      },
      side: "CREDIT",
      amount: { $numberDecimal: "1000.00" },
      currency: "USD",
      functionalAmount: { $numberDecimal: "1000.00" },
      runningBalance: { $numberDecimal: "3450.00" },
      valueDate: { $date: "2026-04-15T00:00:00Z" },
      postingDate: { $date: "2026-04-15T10:23:45Z" },
      transactionType: "PAYMENT_IN",
      status: "POSTED",
      sourceReference: {
        sourceSystem: "PAYMENT_ORDER",
        sourceId: "PAY-20260415-0042",
        sourceType: "PAYMENT",
        sourceCollection: "payments",
      },
      description: "Inbound SWIFT MT103 — credit to customer account ACC-001234",
    },
    designDecisionIds: [1, 2, 6, 7, 8],
  },

  bianMappings: {
    mongoAlias: "bianMappings",
    description:
      "Versioned BIAN field-name catalog. Two documents: (1) bian-mapping-mutable — living document for business-logic collections, updated in place, consumers always read latest; (2) bian-mapping-immutable-v{N} — pinned snapshot for ledger collections (journalEntries, subLedgerEntries). Each posted journal records the immutable mapping version it was canonicalized against; the v{N} document MUST never be modified after first write. New mapping versions are inserted as new documents.",
    immutable: false,
    bianClassification: {
      sd: "ReferenceDataDirectory",
      cr: "BianMappingCatalog",
      bq: "VersionedMappingEntry",
      pattern: "Reference",
    },
    fields: [
      { name: "_id", type: "objectId", required: true, note: "MongoDB PK" },
      { name: "$meta.documentId", type: "string", required: true, note: "Stable identifier. mutable: 'bian-mapping-mutable'. immutable: 'bian-mapping-immutable-v{N}'. Unique." },
      { name: "$meta.versionType", type: "string", required: true, note: "'mutable' | 'immutable' — drives write-policy enforcement" },
      { name: "$meta.version", type: "string", required: true, note: "'latest' for mutable; 'v1.0', 'v1.1', 'v2.0' for immutable" },
      { name: "$meta.pinnedVersion", type: "string", required: false, note: "Sparse — set on immutable docs only. Self-reference convenience field." },
      { name: "$meta.pinnedAt", type: "date", required: false, note: "Sparse — when this immutable snapshot was first written" },
      { name: "$meta.lastUpdatedAt", type: "date", required: true, note: "Mutable: latest edit. Immutable: equal to pinnedAt — must not move." },
      { name: "$meta.source", type: "string", required: true, note: "Origin spec the mapping was generated from" },
      { name: "$meta.bianVersion", type: "string", required: true, note: "BIAN reference version e.g. v14" },
      { name: "$meta.primaryDatabase", type: "string", required: true, note: "Default DB for collections in this catalog" },
      { name: "$meta.generatedFrom", type: "string", required: true, note: "Toolchain provenance — e.g. validator.$jsonSchema bianName annotations" },
      { name: "$meta.description", type: "string", required: true, note: "Human-readable description of the catalog scope and write-policy" },
      { name: "$meta.collectionDatabaseMap", type: "object", required: true, note: "{ collectionName: databaseName } — resolves cross-DB mappings (e.g. loans → fsi-agentic-lending)" },
      { name: "<collectionName>", type: "object", required: true, note: "Top-level keys are collection names. Each maps mongo field path → BIAN canonical name. Dotted paths (a.b.c) and array paths (xs[].y) are supported." },
    ],
    indexes: [
      { name: "idx_document_id_unique", key: "{ '$meta.documentId': 1 }", unique: true },
      { name: "idx_version_type", key: "{ '$meta.versionType': 1 }" },
      { name: "idx_version_type_version", key: "{ '$meta.versionType': 1, '$meta.version': 1 }" },
    ],
    sampleDocuments: [
      {
        label: "Immutable — pinned snapshot",
        kind: "immutable",
        accent: "yellow",
        documentId: "bian-mapping-immutable-v1.0",
        version: "v1.0",
        caption:
          "Ledger collections only (journalEntries, subLedgerEntries). Write-once; every posted journal pins this exact mapping version. Modifying this document silently rewrites the historical audit trail.",
        scope: "journalEntries · subLedgerEntries",
        doc: {
          $meta: {
            documentId: "bian-mapping-immutable-v1.0",
            versionType: "immutable",
            version: "v1.0",
            pinnedVersion: "v1.0",
            pinnedAt: "2026-05-07",
            lastUpdatedAt: "2026-05-07",
            source: "Consolidated-CB_TS360_Port_Pay_Lend_OpFin.json (v1.0-combined)",
            bianVersion: "v14",
            primaryDatabase: "leafy_bank_bian",
            generatedFrom: "validator.$jsonSchema bianName annotations, walked recursively per collection",
            description: "PINNED SNAPSHOT v1.0 — Ledger collections only (journalEntries, subLedgerEntries). Immutable; must NOT be modified.",
            collectionDatabaseMap: {
              journalEntries: "leafy_bank_bian",
              subLedgerEntries: "leafy_bank_bian",
            },
          },
          journalEntries: {
            journalId: "FinancialBookingLogIdentifier",
            idempotencyKey: "FinancialBookingLogIdempotencyKey",
            periodCode: "FinancialBookingLogPeriodCode",
            valueDate: "FinancialBookingLogValueDate",
            postingDate: "FinancialBookingLogPostingDateTime",
            journalType: "FinancialBookingLogType",
            status: "FinancialBookingLogLifecycleStatusType",
            currency: "FinancialBookingLogCurrencyCode",
            totalAmount: "FinancialBookingLogTotalAmount",
            description: "FinancialBookingLogDescriptionText",
            sourceReference: "FinancialBookingLogSourceReference",
            entries: "LedgerPostingRecord",
            reversalOf: "FinancialBookingLogReversalOfReference",
            reversedBy: "FinancialBookingLogReversedByReference",
            approvedBy: "FinancialBookingLogApprovedByReference",
            approvedAt: "FinancialBookingLogApprovalDateTime",
            postedBy: "FinancialBookingLogPostedByReference",
            periodName: "FinancialBookingLogPeriodName",
          },
          subLedgerEntries: {
            subLedgerId: "LedgerPostingIdentifier",
            idempotencyKey: "LedgerPostingIdempotencyKey",
            journalEntryId: "LedgerPostingFinancialBookingLogReference",
            periodCode: "FinancialBookingLogPeriodCode",
            subLedgerType: "LedgerPostingSubLedgerTypeCode",
            controlAccountCode: "LedgerPostingFinancialAccountCode",
            entityReference: "LedgerPostingEntityReference",
            side: "LedgerPostingDebitCreditType",
            amount: "LedgerPostingTransactionAmount",
            currency: "LedgerPostingCurrencyCode",
            functionalAmount: "LedgerPostingFunctionalAmount",
            runningBalance: "LedgerPostingRunningBalance",
            valueDate: "LedgerPostingValueDate",
            postingDate: "LedgerPostingPostingDateTime",
            transactionType: "LedgerPostingTransactionType",
            status: "LedgerPostingLifecycleStatusType",
            sourceReference: "LedgerPostingSourceReference",
            description: "LedgerPostingDescriptionText",
            reversalOf: "LedgerPostingReversalOfReference",
            reversedBy: "LedgerPostingReversedByReference",
          },
        },
      },
      {
        label: "Mutable — living catalog",
        kind: "mutable",
        accent: "blue",
        documentId: "bian-mapping-mutable",
        version: "latest",
        caption:
          "Business-logic collections (customers, accounts, payments, fraud, lending, portfolio). Updated in place — consumers always read the latest. Truncated below; ~300 field mappings across 11 collections.",
        scope: "11 business-logic collections",
        doc: {
          $meta: {
            documentId: "bian-mapping-mutable",
            versionType: "mutable",
            version: "latest",
            pinnedVersion: null,
            pinnedAt: null,
            lastUpdatedAt: "2026-05-07",
            source: "Consolidated-CB_TS360_Port_Pay_Lend_OpFin.json (v1.0-combined)",
            bianVersion: "v14",
            primaryDatabase: "leafy_bank_bian",
            generatedFrom: "validator.$jsonSchema bianName annotations, walked recursively per collection",
            description: "LIVING DOCUMENT — Mongo camelCase field path -> BIAN v14 canonical name. Evolves with schema changes; consumers always fetch latest. Ledger collections (journalEntries, subLedgerEntries) live in bian-mapping-immutable.",
            collectionDatabaseMap: {
              customers: "leafy_bank_bian",
              accounts: "leafy_bank_bian",
              payments: "leafy_bank_bian",
              fraudEvaluation: "leafy_bank_bian",
              fraudResolution: "leafy_bank_bian",
              portfolioAllocation: "leafy_bank_bian",
              portfolioPerformance: "leafy_bank_bian",
              loans: "fsi-agentic-lending",
              creditReports: "fsi-agentic-lending",
              canonicalJsonStorage: "leafy_bank_bian",
              glAccounts: "leafy_bank_bian",
            },
          },
          glAccounts: {
            accountCode: "FinancialAccountCode",
            accountName: "FinancialAccountName",
            accountType: "FinancialAccountType",
            normalBalance: "FinancialAccountNormalBalanceType",
            parentAccountCode: "ParentAccountReference",
            level: "AccountHierarchyLevel",
            isPostingAccount: "FinancialAccountPostingIndicator",
            currency: "FinancialAccountCurrencyCode",
            subLedgerType: "SubLedgerTypeCode",
            status: "FinancialAccountStatusType",
            description: "FinancialAccountDescriptionText",
          },
          "// ...": "10 more collections truncated — customers, accounts, payments, fraudEvaluation, fraudResolution, portfolioAllocation, portfolioPerformance, loans, creditReports, canonicalJsonStorage. ~300 field mappings total.",
        },
      },
    ],
    designDecisionIds: [12, 13, 14],
  },
};

export const DESIGN_DECISIONS = [
  { id: 0, topic: "MVP Scope Decision", decision: "MVP deploys 3 collections: glAccounts, journalEntries, subLedgerEntries. accountingPeriods excluded — period tracked via periodCode string on each entry.", rationale: "Minimum viable ledger: post transactions, query by account, query by period, trace back to source, drill down to entity level. Period lifecycle management (open/close) added in Phase 2." },
  { id: 1, topic: "Idempotency Key", decision: "Every journalEntry and subLedgerEntry requires an idempotencyKey with a unique index. The client generates a UUID per business event and includes it in every POST.", rationale: "Payment systems retry on timeout. Without idempotency, the same payment could be posted twice. The unique index is the enforcement mechanism — not application code." },
  { id: 2, topic: "Immutability of Posted Entries", decision: "Once status=POSTED, journal and sub-ledger entries are never modified or deleted. Errors are corrected by posting a REVERSAL journal which creates equal and opposite entries.", rationale: "Audit trail integrity. Regulators and auditors require an immutable ledger." },
  { id: 3, topic: "Double-Entry Balance Enforcement", decision: "Application layer must validate sum(entries where side=DEBIT) == sum(entries where side=CREDIT) before setting status=POSTED. MongoDB $jsonSchema can validate min 2 entries exist but cannot enforce balance — this must be done in service code.", rationale: "Core accounting principle. An unbalanced journal corrupts the trial balance." },
  { id: 4, topic: "Period Validation", decision: "MVP: application code validates that periodCode represents an open period before setting status=POSTED. Phase 2: validation moves to a DB-level check against accountingPeriods collection.", rationale: "Prevents backdating after period close which would corrupt financial statements." },
  { id: 5, topic: "Decimal128 for All Amounts", decision: "All amount fields use BSON Decimal128 (not double). Applies to amount, totalAmount, functionalAmount, runningBalance, fxRate.", rationale: "IEEE 754 floating point loses precision in financial calculations. Decimal128 is exact to 34 significant digits — required for regulatory-grade reporting." },
  { id: 6, topic: "Sub-Ledger to GL Relationship", decision: "subLedgerEntries roll up to a GL control account. The sum of all subLedgerEntries for a controlAccountCode must equal the GL balance of that account.", rationale: "Standard subledger accounting pattern. GL stays clean (summary); subledger has entity-level detail. Enables drill-down from GL → subledger → source document." },
  { id: 7, topic: "Source Reference", decision: "Every journal and sub-ledger entry carries a sourceReference (sourceSystem, sourceId, sourceType, sourceCollection). Links the accounting entry back to the originating business event.", rationale: "Full traceability: payment → journal entry → sub-ledger entry → GL balance. Required for audit, dispute resolution, and regulatory reporting." },
  { id: 8, topic: "Running Balance", decision: "runningBalance on subLedgerEntries is optional but recommended for high-query accounts. Updated atomically using findOneAndUpdate with $inc on a separate accountBalances document.", rationale: "Balance queries across millions of entries using aggregation are slow. A separate running balance document per entity enables O(1) balance lookups." },
  { id: 9, topic: "BIAN Mapping", decision: "All collections map to BIAN Financial Accounting Service Domain. Control Record: FinancialBookingLog. BQ: LedgerPosting. Pattern: Management.", rationale: "Consistent with BIAN v14 Financial Accounting SD structure." },
  { id: 10, topic: "MVP Collection Scope", decision: "Phase 1 MVP: glAccounts + journalEntries. Phase 2: accountingPeriods + subLedgerEntries.", rationale: "glAccounts is required immediately; journalEntries is the core posting mechanism. periodCode is stored as a plain string on journalEntries in all phases." },
  { id: 11, topic: "BIAN v14 CR — FinancialBookingLog", decision: "Control Record corrected to FinancialBookingLog per BIAN v14 reference data. SD FinancialAccounting confirmed correct. BIAN defines 1 BQ: LedgerPosting.", rationale: "Validated against BIAN v14 Service Domains reference ODS file, May 2026." },
  { id: 12, topic: "Versioned Mapping Catalog", decision: "BIAN field-name catalog is split into two documents in the bianMappings collection: a single mutable doc (versionType='mutable', version='latest', updated in place) for business-logic collections; one immutable doc per published version (versionType='immutable', documentId='bian-mapping-immutable-v{N}') for ledger collections. New mapping versions are inserted as new documents — never as updates to an existing immutable doc.", rationale: "Posted journals are append-only and reference the mapping version they were canonicalized against. If the v1.0 mapping mutated after the fact, every historical journal pointing at v1.0 would silently observe a new schema — breaking the audit trail. Mirrors the schema-registry pattern (Confluent, Avro): versions are content-addressed snapshots, not mutable rows." },
  { id: 13, topic: "Immutable Mapping Enforcement", decision: "Defense in depth: (a) application layer rejects updateOne / replaceOne against any document where $meta.versionType='immutable'; (b) unique index on $meta.documentId — and the documentId encodes the version — prevents accidental upsert overwrite; (c) writes go through a single ingestion service that stamps pinnedAt = lastUpdatedAt at first insert and refuses any later mutation.", rationale: "Application code drifts; indexes are durable. Combining both removes any single point at which a careless write could rewrite history." },
  { id: 14, topic: "Ledger ↔ Mapping Pinning", decision: "Every journalEntry and subLedgerEntry carries the pinned mapping version (e.g. mappingVersion='v1.0') at write time. Readers ALWAYS resolve historical entries against the pinned version's immutable mapping doc — never auto-upgrade to a newer version. The mutable catalog is read for business-logic collections only.", rationale: "Two different temporal contracts: ledger entries live in the past and must be interpretable against their original schema; business-logic entities live in the present and benefit from the latest field naming." },
];

// Helper for DocumentSnippet — given a collection key, returns
// { fieldName: { bian, note, type, required } } so the inline JSON
// renderer can wrap each field name with an InfoSprinkle.
export function aliasMap(collectionKey) {
  const c = COLLECTIONS[collectionKey];
  if (!c) return {};
  const map = {};
  for (const f of c.fields) {
    map[f.name] = { bian: f.bian, note: f.note, type: f.type, required: f.required };
  }
  if (c.entryFields) {
    for (const f of c.entryFields) {
      map[`entries[].${f.name}`] = { bian: f.bian, note: f.note, type: f.type };
      // Also expose un-prefixed for convenience when rendering an entry alone
      if (!map[f.name]) {
        map[f.name] = { bian: f.bian, note: f.note, type: f.type };
      }
    }
  }
  return map;
}

// ─────────────────────────────────────────────────────────────────────────────
// Business-logic collections — derived from the BIAN v14 alias map.
//
// Single source of truth: BUSINESS_LOGIC_BIAN_MAP below mirrors the canonical
// Mongo path → BIAN field-name mapping (bian-alias-map.json). Field rows are
// generated mechanically; per-collection metadata (description, BIAN
// classification, DB override) is hand-curated in BUSINESS_LOGIC_META.
//
// Ledger collections (glAccounts, journalEntries, subLedgerEntries) keep
// their richer hand-curated entries above — those carry indexes, sample
// documents, and design decisions that the alias map alone can't express.
// ─────────────────────────────────────────────────────────────────────────────

function inferType(path, bian, allPaths) {
  // Array detection: a sibling path of the form `${path}[].x` proves this is an array
  if (allPaths.some((p) => p.startsWith(path + "[].") || p === path + "[]")) return "array";
  if (path.endsWith("[]")) return "array";
  if (!bian) return "string";
  if (/(?:Record|Snapshot|Catalogue|Resolution|Profile|Document|Audit)$/.test(bian)) return "object";
  if (/Indicator$/.test(bian)) return "bool";
  if (/(?:DateTime|Date)$/.test(bian)) return "date";
  if (/(?:Amount|Score|Rate|Decimal)$/.test(bian)) return "decimal";
  if (/(?:Number|Value|Level|Hierarchy|Count)$/.test(bian)) return "number";
  return "string";
}

const BUSINESS_LOGIC_BIAN_MAP = {
  customers: {
    customerId: "CustomerReference",
    status: "PartyApexStatus",
    type: "PartyType",
    segment: "CustomerSegmentType",
    since: "CustomerSinceDate",
    rmId: "PartyRelationshipManagerReference",
    identification: "PartyIdentification",
    "identification.userName": "PartyLoginIdentifier",
    "identification.legalName": "PartyLegalName",
    "identification.firstName": "PartyNameGivenName",
    "identification.lastName": "PartyNameFamilyName",
    "identification.namePrefix": "PartyNamePrefix",
    "identification.tradingName": "PartyTradingNameList",
    "identification.dateOfBirth": "PartyDateOfBirthDate",
    "identification.countryOfBirth": "PartyCountryOfBirthCode",
    "identification.nationality": "PartyNationalityCode",
    "identification.nationalId": "NationalIdentityNumber",
    "identification.nationalIdType": "NationalIdentityNumberType",
    "identification.taxId": "TaxIdentificationNumber",
    "identification.civilStatus": "PartyMaritalStatusType",
    "identification.jobTitle": "PartyEmploymentPositionText",
    employment: "PartyEmploymentRecord",
    "employment.employer": "PartyEmployerRecord",
    "employment.employer.name": "PartyEmployerName",
    "employment.employer.payrollId": "PartyEmployerPayrollIdentifier",
    "employment.employer.startDate": "PartyEmploymentStartDate",
    "employment.jobTitle": "PartyEmploymentPositionText",
    "employment.employmentType": "PartyEmploymentType",
    "employment.income": "PartyIncomeRecord",
    "employment.income.amount": "PartyIncomeAmount",
    "employment.income.currency": "PartyIncomeCurrencyCode",
    "employment.income.frequency": "PartyIncomeFrequencyType",
    contact: "PartyContactRecord",
    "contact.email": "PartyContactEmailAddress",
    "contact.phone": "PartyContactPhoneNumber",
    "contact.preferredLanguage": "PreferredLanguageCode",
    "contact.preferredChannel": "PreferredCommunicationChannelType",
    "contact.addresses": "PartyAddressRecord",
    "contact.addresses[].type": "PartyAddressType",
    "contact.addresses[].isPrimary": "PartyAddressIsPrimaryIndicator",
    "contact.addresses[].line1": "PartyAddressLine1Text",
    "contact.addresses[].line2": "PartyAddressLine2Text",
    "contact.addresses[].city": "PartyAddressCityText",
    "contact.addresses[].state": "PartyAddressStateText",
    "contact.addresses[].postcode": "PartyAddressPostalCode",
    "contact.addresses[].country": "PartyAddressCountryCode",
    "contact.addresses[].validFrom": "PartyAddressValidFromDate",
    "contact.addresses[].validTo": "PartyAddressValidToDate",
    "contact.addresses[].residentialStatus": "PartyResidenceStatusType",
    kyc: "CustomerKYCRecord",
    "kyc.status": "CustomerKYCProcedureStatus",
    "kyc.level": "CustomerKYCVerificationLevelType",
    "kyc.riskRating": "CustomerCreditRatingAssessment",
    "kyc.verifiedAt": "CustomerKYCVerificationDate",
    "kyc.nextReviewAt": "CustomerKYCNextReviewDate",
    "kyc.documents": "CustomerKYCDocumentRecord",
    "kyc.documents[].docType": "CustomerKYCDocumentType",
    "kyc.documents[].docRef": "CustomerKYCDocumentReference",
    "kyc.documents[].issuedBy": "CustomerKYCDocumentIssuingAuthorityText",
    "kyc.documents[].issuedAt": "CustomerKYCDocumentIssuedDate",
    "kyc.documents[].expiresAt": "CustomerKYCDocumentExpiryDate",
    "kyc.documents[].verifiedAt": "CustomerKYCDocumentVerifiedDate",
    "kyc.documents[].verifiedBy": "CustomerKYCDocumentVerifiedByReference",
    gender: "PartyGenderType",
    residency: "PartyResidencyCountryCode",
    identifiers: "PartyIdentifierRecord",
    "identifiers[].passportNumber": "PassportNumber",
    "identifiers[].lei": "LegalEntityIdentifier",
    "identifiers[].incorporationNumber": "PartyIncorporationNumber",
    "identifiers[].incorporationDate": "PartyIncorporationDate",
    "identifiers[].incorporationCountry": "PartyIncorporationJurisdictionCode",
    BankRelations: "PartyBankRelationsRecord",
    "BankRelations.customerInfo": "PartyBankRelationsRecord",
    "BankRelations.customerInfo.customerSince": "PartyCustomerSinceDate",
    "BankRelations.customerInfo.segments": "CustomerSegmentList",
    "BankRelations.customerInfo.products": "CustomerProductHoldingList",
    "BankRelations.customerInfo.notes": "CustomerNotesText",
    consents: "PartyConsentRecord",
    "consents[].consentType": "PartyConsentType",
    "consents[].granted": "PartyConsentGrantedIndicator",
    "consents[].grantedAt": "PartyConsentGrantedDateTime",
    "consents[].expiresAt": "PartyConsentExpiryDate",
    "consents[].channel": "PartyConsentChannelType",
    createdAt: "RecordCreateDateTime",
    updatedAt: "RecordUpdateDateTime",
    createdBy: "RecordCreatedByReference",
    version: "RecordVersionNumber",
    sourceSystem: "SourceSystemReference",
  },

  accounts: {
    accountId: "CurrentAccountReference",
    accountNumber: "CurrentAccountNumber",
    accountIdentificationType: "AccountIdentificationSchemeType",
    type: "CurrentAccountType",
    description: "CurrentAccountDescriptionText",
    status: "CurrentAccountApexStatus",
    customerSnapshot: "CustomerSnapshotRecord",
    "customerSnapshot.customerId": "CustomerReference",
    productId: "ProductReference",
    branchId: "BranchReference",
    accountBank: "CurrentAccountIssuingBankReference",
    currency: "CurrentAccountCurrencyCode",
    openedAt: "CurrentAccountOpenDate",
    closedAt: "CurrentAccountCloseDate",
    maturesAt: "CurrentAccountMaturityDate",
    linkedCardIds: "linkedCardReferences",
    linkedMandateIds: "linkedMandateReferences",
    balance: "CurrentAccountBalanceRecord",
    "balance.current": "CurrentAccountBalanceAmount",
    "balance.available": "CurrentAccountAvailableBalanceAmount",
    "balance.ledger": "CurrentAccountLedgerBalanceAmount",
    "balance.hold": "CurrentAccountHoldAmount",
    "balance.overdraftLimit": "CurrentAccountOverdraftLimitAmount",
    "balance.updatedAt": "CurrentAccountBalanceUpdateDateTime",
    interest: "CurrentAccountInterestRecord",
    "interest.rate": "CurrentAccountInterestRateValue",
    "interest.accrualMethod": "CurrentAccountInterestAccrualMethodType",
    "interest.accrued": "CurrentAccountAccruedInterestAmount",
    "interest.lastAccrualAt": "CurrentAccountInterestLastAccrualDate",
    "interest.nextPaymentAt": "CurrentAccountInterestNextPaymentDate",
    "interest.paymentAccountId": "CurrentAccountInterestPaymentAccountReference",
    signatories: "CurrentAccountSignatoryRecord",
    "signatories[].customerId": "AccountSignatoryPartyReference",
    "signatories[].type": "AccountSignatoryType",
    "signatories[].signingRule": "AccountSignatorySigningRuleType",
    "signatories[].addedAt": "AccountSignatoryAddedDate",
    restrictions: "CurrentAccountRestrictionRecord",
    "restrictions[].type": "AccountRestrictionType",
    "restrictions[].reason": "AccountRestrictionReasonText",
    "restrictions[].appliedAt": "AccountRestrictionAppliedDate",
    "restrictions[].appliedBy": "AccountRestrictionAppliedByReference",
    "restrictions[].expiresAt": "AccountRestrictionExpiryDate",
    statement: "CurrentAccountStatementRecord",
    "statement.frequency": "AccountStatementFrequencyType",
    "statement.deliveryChannel": "AccountStatementDeliveryChannelType",
    "statement.lastGeneratedAt": "AccountStatementLastGeneratedDate",
    "statement.nextScheduledAt": "AccountStatementNextScheduledDate",
    gl: "CurrentAccountGLMappingRecord",
    "gl.accountCode": "AccountGLAccountReference",
    "gl.costCenter": "AccountCostCenterReference",
    "gl.profitCenter": "AccountProfitCenterReference",
    createdAt: "RecordCreateDateTime",
    updatedAt: "RecordUpdateDateTime",
    createdBy: "RecordCreatedByReference",
    version: "RecordVersionNumber",
    sourceSystem: "SourceSystemReference",
  },

  payments: {
    paymentId: "PaymentOrderReference",
    endToEndId: "PaymentEndToEndIdentifier",
    instructionId: "PaymentInstructionIdentifier",
    txnId: "PaymentTransactionIdentifier",
    uetr: "PaymentUniqueTransactionReference",
    msgId: "PaymentMessageIdentifier",
    customerId: "CustomerReference",
    initiatedAt: "PaymentInitiationDateTime",
    type: "PaymentType",
    rail: "PaymentRailType",
    status: "PaymentApexStatus",
    priority: "PaymentPriorityType",
    instructedAmount: "PaymentInstructedAmount",
    instructedCurrency: "PaymentInstructedCurrencyCode",
    amount: "PaymentTransactionAmount",
    currency: "PaymentTransactionCurrencyCode",
    fxRate: "PaymentFXConversionRateValue",
    chargeBearer: "PaymentChargeBearerType",
    categoryPurpose: "PaymentCategoryPurposeCode",
    debtor: "PaymentDebtorRecord",
    "debtor.accountId": "DebtorAccountReference",
    "debtor.accountNo": "DebtorAccountNumber",
    "debtor.iban": "DebtorInternationalBankAccountNumber",
    "debtor.name": "DebtorPartyName",
    "debtor.bic": "DebtorBankIdentifierCode",
    "debtor.address": "DebtorPostalAddressText",
    "debtor.accountType": "DebtorAccountType",
    creditor: "PaymentCreditorRecord",
    "creditor.accountId": "CreditorAccountReference",
    "creditor.accountNo": "CreditorAccountNumber",
    "creditor.iban": "CreditorInternationalBankAccountNumber",
    "creditor.name": "CreditorPartyName",
    "creditor.bic": "CreditorBankIdentifierCode",
    "creditor.bankName": "CreditorBankName",
    "creditor.bankCountry": "CreditorBankCountryCode",
    "creditor.address": "CreditorPostalAddressText",
    "creditor.accountType": "CreditorAccountType",
    remittance: "PaymentRemittanceRecord",
    "remittance.unstructured": "RemittanceUnstructuredInformationText",
    "remittance.reference": "RemittanceStructuredReferenceText",
    "remittance.invoiceNo": "RemittanceInvoiceIdentifier",
    "remittance.purposeCode": "RemittancePurposeCode",
    correspondent: "PaymentCorrespondentBankingRecord",
    "correspondent.correspondentBic": "CorrespondentBankIdentifierCode",
    "correspondent.intermediaryBic": "IntermediaryBankIdentifierCode",
    "correspondent.regulatoryReports": "PaymentRegulatoryReportingRecord",
    "correspondent.sanctionsCheck": "PaymentSanctionsCheckRecord",
    "correspondent.sanctionsCheck.status": "SanctionsCheckStatus",
    "correspondent.sanctionsCheck.checkedAt": "SanctionsCheckDateTime",
    "correspondent.sanctionsCheck.provider": "SanctionsCheckProviderReference",
    cardTxn: "PaymentCardTransactionRecord",
    "cardTxn.cardId": "IssuedDeviceReference",
    "cardTxn.maskedPan": "CardPANMaskedIdentifier",
    "cardTxn.network": "CardNetworkType",
    "cardTxn.txnType": "CardTransactionType",
    "cardTxn.merchantId": "MerchantReference",
    "cardTxn.merchantName": "MerchantName",
    "cardTxn.mcc": "MerchantCategoryCode",
    "cardTxn.terminalId": "TerminalReference",
    "cardTxn.authCode": "CardAuthorisationCode",
    "cardTxn.isCardPresent": "CardPresentIndicator",
    "cardTxn.isEcommerce": "ECommerceTransactionIndicator",
    rtp: "PaymentRTPRecord",
    "rtp.network": "RTPNetworkType",
    "rtp.rfpId": "RTPRequestForPaymentReference",
    "rtp.proxyType": "RTPProxyIdentifierType",
    "rtp.proxyValue": "RTPProxyIdentifierValue",
    "rtp.isRFP": "RTPRequestForPaymentIndicator",
    clearing: "PaymentClearingAndSettlementRecord",
    "clearing.receivedAt": "PaymentReceivedDateTime",
    "clearing.validatedAt": "PaymentValidatedDateTime",
    "clearing.authorisedAt": "PaymentAuthorisedDateTime",
    "clearing.submittedAt": "PaymentSubmittedToNetworkDateTime",
    "clearing.settlementDate": "PaymentSettlementDate",
    "clearing.settledAt": "PaymentSettledDateTime",
    "clearing.batchRef": "PaymentClearingBatchReference",
    "clearing.networkRef": "PaymentClearingNetworkReference",
    "clearing.networkCode": "PaymentNetworkResponseCode",
    "clearing.statusCode": "PaymentStatusReasonCode",
    "clearing.rejectionCode": "PaymentRejectionReasonCode",
    "clearing.returnCode": "PaymentReturnReasonCode",
    fees: "PaymentFeesRecord",
    "fees[].type": "PaymentFeeType",
    "fees[].amount": "PaymentFeeAmount",
    "fees[].currency": "PaymentFeeCurrencyCode",
    "fees[].chargedTo": "PaymentFeeChargeBearerType",
    fraud: "PaymentFraudEvaluationRecord",
    "fraud.alertId": "FraudEvaluationReference",
    "fraud.score": "PaymentFraudScore",
    "fraud.decision": "PaymentFraudDecisionType",
    "fraud.rulesFired": "PaymentFraudRulesTriggeredText",
    "fraud.checkedAt": "FraudEvaluationDateTime",
    initiation: "PaymentInitiationAuditRecord",
    "initiation.initiatedAt": "PaymentInitiationDateTime",
    "initiation.initiatedBy": "PaymentInitiatingPartyReference",
    "initiation.channel": "PaymentInitiationChannelType",
    "initiation.ipAddress": "PaymentInitiationIPAddressText",
    "initiation.deviceId": "PaymentInitiationDeviceReference",
    createdAt: "RecordCreateDateTime",
    updatedAt: "RecordUpdateDateTime",
    version: "RecordVersionNumber",
    sourceSystem: "SourceSystemReference",
  },

  fraudEvaluation: {
    transactionId: "FraudEvaluationSubjectReference",
    customerId: "CustomerReference",
    timestamp: "FraudEvaluationDateTime",
    status: "FraudEvaluationApexStatus",
    riskScore: "FraudEvaluationCompositeScore",
    fromEntityId: "FraudEvaluationOriginatingPartyReference",
    fromEntityType: "FraudEvaluationOriginatingPartyType",
    fromEntityName: "FraudEvaluationOriginatingPartyName",
    toEntityId: "FraudEvaluationBeneficiaryPartyReference",
    toEntityType: "FraudEvaluationBeneficiaryPartyType",
    toEntityName: "FraudEvaluationBeneficiaryPartyName",
    amount: "FraudEvaluationTransactionAmount",
    currency: "FraudEvaluationTransactionCurrencyCode",
    transactionType: "FraudEvaluationTransactionType",
    channel: "FraudEvaluationChannelType",
    description: "FraudEvaluationDescriptionText",
    tags: "FraudEvaluationClassificationTagText",
    flagged: "FraudEvaluationFlagIndicator",
    additionalDetails: "FraudEvaluationExtensionRecord",
    paymentRail: "FraudEvaluationPaymentRailType",
  },

  fraudResolution: {
    caseId: "FraudCaseProcedureReference",
    caseType: "FraudCaseProcedureType",
    customerId: "CustomerReference",
    status: "FraudCaseProcedureApexStatus",
    riskIndicators: "FraudCaseRiskIndicatorText",
    relatedTransactionIds: "FraudCaseRelatedTransactionReference",
    relatedAlertIds: "FraudEvaluationReference",
    caseResolution: "CaseResolution",
    "caseResolution.reportType": "RegulatoryReportType",
    "caseResolution.filingDeadline": "FilingDeadlineDate",
    "caseResolution.submittedAt": "FilingSubmittedDateTime",
    "caseResolution.filingReference": "FilingReferenceIdentifier",
    "caseResolution.regulatoryAuthority": "RegulatoryAuthorityText",
  },

  loans: {
    loansId: "ConsumerLoanApplicationIdentifier",
    borrowerIds: "CustomerReference",
    borrowerNames: "CustomerName",
    loanAmount: "ConsumerLoanAmount",
    purchasePrice: "ConsumerLoanCollateralPropertyValue",
    downPayment: "ConsumerLoanDownPaymentAmount",
    existingMonthlyDebt: "ConsumerLoanExistingMonthlyDebtAmount",
    product: "ConsumerLoanProductType",
    status: "ConsumerLoanApexStatus",
    statusHistory: "ConsumerLoanStatusHistoryRecord",
    "statusHistory[].status": "ConsumerLoanStatusType",
    "statusHistory[].timestamp": "ConsumerLoanStatusChangeDateTime",
    "statusHistory[].detail": "ConsumerLoanStatusChangeDescriptionText",
    incomeSummary: "ConsumerLoanAffordabilityRecord",
    "incomeSummary.primary": "ConsumerLoanPrimaryIncomeAmount",
    "incomeSummary.coApplicant": "ConsumerLoanCoApplicantIncomeAmount",
    "incomeSummary.combinedGross": "ConsumerLoanCombinedGrossIncomeAmount",
    property: "ConsumerLoanCollateralRecord",
    "property.address": "ConsumerLoanCollateralAddressText",
    "property.type": "ConsumerLoanCollateralPropertyType",
    "property.purchasePrice": "ConsumerLoanCollateralPurchasePrice",
    "property.annualTax": "ConsumerLoanCollateralAnnualTaxAmount",
    createdAt: "RecordCreateDateTime",
    updatedAt: "RecordUpdateDateTime",
    seedComplete: "impl_SeedCompleteIndicator",
  },

  creditReports: {
    borrowerId: "CustomerReference",
    borrowerName: "CustomerName",
    score: "CustomerCreditRatingValue",
    bureau: "ExternalCreditBureauReference",
    accounts: "CustomerCreditTradelineRecord",
    "accounts[].creditor": "CustomerCreditTradelineCreditorName",
    "accounts[].balance": "CustomerCreditTradelineOutstandingBalance",
    "accounts[].monthlyPayment": "CustomerCreditTradelineMonthlyPaymentAmount",
    "accounts[].status": "CustomerCreditTradelineStatusType",
    totalOutstanding: "CustomerCreditTotalOutstandingAmount",
    paymentHistory: "CustomerCreditPaymentHistorySummaryText",
    inquiries: "CustomerCreditInquiryRecord",
    derogatoryItems: "CustomerCreditDerogatoryItemRecord",
    pulledAt: "ExternalCreditBureauReportDate",
    createdAt: "RecordCreateDateTime",
  },

  portfolioAllocation: {
    symbol: "InvestmentPortfolioInstrumentReference",
    binanceSymbol: "InvestmentPortfolioInstrumentExchangeSymbolCode",
    description: "InvestmentPortfolioInstrumentDescriptionText",
    assetType: "InvestmentPortfolioAssetClassType",
    allocationPercentage: "InvestmentPortfolioAllocationPercentageText",
    allocationNumber: "InvestmentPortfolioAllocationPercentageValue",
    allocationDecimal: "InvestmentPortfolioAllocationRate",
  },

  portfolioPerformance: {
    date: "InvestmentPortfolioAnalysisDateTime",
    percentageOfDailyReturn: "InvestmentPortfolioDailyReturnValue",
    percentageOfCumulativeReturn: "InvestmentPortfolioCumulativeReturnValue",
  },

  canonicalJsonStorage: {
    conversionId: "PaymentMessageConversionType",
    createdAt: "RecordCreateDateTime",
    jsonData: "OrderInitiationRecord",
    "jsonData.transactionRef": "PaymentEndToEndIdentifier",
    "jsonData.bankOperationCode": "PaymentBankOperationCode",
    "jsonData.valueDate": "PaymentValueDate",
    "jsonData.currency": "PaymentTransactionCurrencyCode",
    "jsonData.amount": "PaymentTransactionAmount",
    "jsonData.debtorAccount": "DebtorAccountNumber",
    "jsonData.debtorName": "DebtorPartyName",
    "jsonData.debtorAddress": "DebtorPostalAddressText",
    "jsonData.creditorAccount": "CreditorAccountNumber",
    "jsonData.creditorName": "CreditorPartyName",
    "jsonData.creditorAddress": "CreditorPostalAddressText",
    "jsonData.chargeBearer": "PaymentChargeBearerType",
    metadata: "ConfirmationRecord",
    "metadata.sourceFormat": "PaymentSourceMessageFormatType",
    "metadata.targetFormat": "PaymentTargetMessageFormatType",
    "metadata.timestamp": "PaymentConversionProcessingDateTime",
    "metadata.processingTimeSeconds": "PaymentConversionProcessingDurationValue",
    "metadata.auditTrail": "PaymentFieldAuditTrailRecord",
    "metadata.lastUpdated": "RecordLastUpdateDateTime",
  },
};

const BUSINESS_LOGIC_META = {
  customers: {
    group: "Payments",
    database: "leafy_bank_bian",
    description:
      "Customer master record. Identification (PII encrypted client-side via Queryable Encryption), employment, contact, KYC, consents, and bank-relations data.",
    bianClassification: { sd: "PartyReferenceDataDirectory", cr: "PartyReferenceDataDirectoryEntry", bq: "PartyAdministration", pattern: "ReferenceData" },
  },
  accounts: {
    group: "Payments",
    database: "leafy_bank_bian",
    description:
      "Current-account fulfilment record — balances, signatories, restrictions, statement schedule, GL mapping. One document per account.",
    bianClassification: { sd: "CurrentAccount", cr: "CurrentAccountFulfillmentArrangement", bq: "AccountAdministration", pattern: "Fulfillment" },
  },
  payments: {
    group: "Payments",
    database: "leafy_bank_bian",
    description:
      "Payment order — initiated, fraud-checked, cleared, and settled. Covers card, RTP, SWIFT/RTGS, and ACH rails with full ISO 20022 fields.",
    bianClassification: { sd: "PaymentOrder", cr: "PaymentOrder", bq: "Initiation", pattern: "Operations" },
  },
  canonicalJsonStorage: {
    group: "Payments",
    database: "leafy_bank_bian",
    description:
      "Canonical JSON storage for payment messages — used by the message-conversion service (e.g. SWIFT MT ⇄ ISO 20022 pacs.008) with field-level audit trail.",
    bianClassification: { sd: "PaymentOrderInitiation", cr: "PaymentOrderInitiationTransaction", bq: "MessageConversion", pattern: "Operations" },
  },
  fraudEvaluation: {
    group: "Fraud",
    database: "leafy_bank_bian",
    description:
      "Fraud risk evaluation per inbound transaction — composite score, originating/beneficiary party, classification tags. Flagged transactions feed fraudResolution.",
    bianClassification: { sd: "FraudEvaluation", cr: "FraudEvaluationProcedure", bq: "Evaluate", pattern: "Operations" },
  },
  fraudResolution: {
    group: "Fraud",
    database: "leafy_bank_bian",
    description:
      "Fraud case lifecycle — investigation, regulatory filing, and resolution. Links back to fraudEvaluation alerts and related transactions.",
    bianClassification: { sd: "FraudResolution", cr: "FraudCaseProcedure", bq: "Investigate", pattern: "Operations" },
  },
  loans: {
    group: "Lending",
    database: "fsi-agentic-lending",
    description:
      "Consumer loan application — amount, collateral, affordability, status history. Lives in the fsi-agentic-lending DB.",
    bianClassification: { sd: "ConsumerLoan", cr: "ConsumerLoanFulfillmentArrangement", bq: "LoanProcessing", pattern: "Fulfillment" },
  },
  creditReports: {
    group: "Lending",
    database: "fsi-agentic-lending",
    description:
      "External credit-bureau report snapshot — score, tradelines, payment history, inquiries, derogatory items.",
    bianClassification: { sd: "CustomerCreditRating", cr: "ExternalCreditBureauReport", bq: "Retrieve", pattern: "Operations" },
  },
  portfolioAllocation: {
    group: "Portfolio",
    database: "leafy_bank_bian",
    description:
      "Target asset allocation per managed investment portfolio — instrument, weight, asset class.",
    bianClassification: { sd: "InvestmentPortfolioPlanning", cr: "ManagedInvestmentPortfolioAgreement", bq: "AllocationManagement", pattern: "Fulfillment" },
  },
  portfolioPerformance: {
    group: "Portfolio",
    database: "leafy_bank_bian",
    description:
      "Daily portfolio analysis — daily and cumulative return values, anchored by analysis date.",
    bianClassification: { sd: "InvestmentPortfolioAnalysis", cr: "ManagedInvestmentPortfolioAnalysis", bq: "PerformanceAnalysis", pattern: "Fulfillment" },
  },
};

for (const [key, aliasMap] of Object.entries(BUSINESS_LOGIC_BIAN_MAP)) {
  const meta = BUSINESS_LOGIC_META[key];
  const allPaths = Object.keys(aliasMap);
  COLLECTIONS[key] = {
    mongoAlias: key,
    description: meta.description,
    immutable: false,
    database: meta.database,
    group: meta.group,
    bianClassification: meta.bianClassification,
    fields: allPaths.map((p) => ({
      name: p,
      type: inferType(p, aliasMap[p], allPaths),
      required: false,
      bian: aliasMap[p],
    })),
    indexes: [],
    sampleDocument: null,
    designDecisionIds: [],
  };
}

// Tag groups on ledger + meta collections so the rail can render section headers
COLLECTIONS.subLedgerEntries.group = "Ledger";
COLLECTIONS.journalEntries.group = "Ledger";
COLLECTIONS.glAccounts.group = "Ledger";
COLLECTIONS.bianMappings.group = "Mappings";

// Convenience for the drawer: list collection keys in canonical demo order,
// grouped by BIAN service domain: Payments → Ledger → Fraud → Portfolio → Lending → Mappings.
export const COLLECTION_KEYS = [
  "customers", "accounts", "payments", "canonicalJsonStorage",
  "subLedgerEntries", "journalEntries", "glAccounts",
  "fraudEvaluation", "fraudResolution",
  "portfolioAllocation", "portfolioPerformance",
  "loans", "creditReports",
  "bianMappings",
];
