// ledgerSchemaV3.js — full schema definitions for v3 collections.
// Same shape as ledgerSchema.js COLLECTIONS so CollectionPanel renders them identically.

export const V3_COLLECTIONS = {

  customers: {
    mongoAlias: "customers",
    description:
      "Customer master record. PII fields (nationalId, taxId, passportNumber) are stored as Queryable Encryption ciphertext (BSON subType:06) — the MongoDB driver encrypts before write and decrypts on authorized read. Equality queries work without server-side decryption. On GDPR erasure, deleting the per-customer DEK permanently orphans the ciphertext.",
    immutable: false,
    bianClassification: {
      sd: "PartyReferenceDataDirectory",
      cr: "CustomerRelationshipRecord",
      bq: "CustomerKYCRecord",
      pattern: "Retrieve",
    },
    fields: [
      { name: "_id",            type: "objectId", required: true,  bian: null,                              note: "MongoDB PK" },
      { name: "customerId",     type: "string",   required: true,  bian: "CustomerReference",               note: "e.g. CUST-FRIDA-001. Indexed unique." },
      { name: "fullName",       type: "string",   required: true,  bian: "CustomerName",                    note: "Display name — not PII-encrypted, low sensitivity" },
      { name: "email",          type: "string",   required: true,  bian: "ContactAddressDetails",           note: "Indexed unique" },
      { name: "nationalId",     type: "binData",  required: true,  bian: "NationalIdentificationNumber",    note: "QE ciphertext (subType:06). Deterministic — equality-queryable." },
      { name: "taxId",          type: "binData",  required: true,  bian: "TaxIdentification",               note: "QE ciphertext (subType:06). Deterministic." },
      { name: "passportNumber", type: "binData",  required: false, bian: "PassportDocumentReference",       note: "QE ciphertext (subType:06). Deterministic." },
      { name: "dekId",          type: "string",   required: true,  bian: null,                              note: "Alt-name reference to __keyVault DEK for this customer" },
      { name: "kycStatus",      type: "string",   required: true,  bian: "CustomerComplianceStatusType",    note: "PENDING | APPROVED | REJECTED | REVIEW_REQUIRED" },
      { name: "createdAt",      type: "date",     required: true  },
      { name: "updatedAt",      type: "date",     required: true  },
    ],
    indexes: [
      { name: "idx_customerId_unique",  key: "{ customerId: 1 }",    unique: true },
      { name: "idx_email_unique",       key: "{ email: 1 }",          unique: true },
      { name: "idx_kycStatus",          key: "{ kycStatus: 1 }" },
      { name: "idx_dekId",              key: "{ dekId: 1 }" },
    ],
    sampleDocument: {
      customerId: "CUST-FRIDA-001",
      fullName: "Frida Karlsson",
      email: "frida.k@mail.se",
      nationalId:     { $binary: { base64: "BhPxK3m9qR4TzJ2N==", subType: "06" } },
      taxId:          { $binary: { base64: "Bh7mN2kLpQ8R...==", subType: "06" } },
      passportNumber: { $binary: { base64: "BhZnT4kLwX9Y...==", subType: "06" } },
      dekId: "DEK-FRIDA-001",
      kycStatus: "APPROVED",
      createdAt: { $date: "2026-05-06T09:00:00Z" },
      updatedAt: { $date: "2026-05-06T09:00:00Z" },
    },
    designDecisionIds: [],
  },

  piiVault: {
    mongoAlias: "piiVault",
    description:
      "PII Vault — one document per encrypted field per customer. Each encryptedValue is deterministically encrypted via MongoDB Queryable Encryption (FLE2), enabling equality queries on ciphertext without server-side decryption. On GDPR crypto-shred, deleting the DEK orphans every document whose dekId matches — no plaintext ever existed on the server.",
    immutable: false,
    bianClassification: {
      sd: "PartyReferenceDataDirectory",
      cr: "CustomerRelationshipRecord",
      bq: "CustomerKYCRecord",
      pattern: "Retrieve",
    },
    fields: [
      { name: "_id",            type: "objectId", required: true,  bian: null,                     note: "MongoDB PK" },
      { name: "customerId",     type: "string",   required: true,  bian: "CustomerReference",      note: "FK → customers.customerId" },
      { name: "fieldName",      type: "string",   required: true,  bian: null,                     note: "nationalId | taxId | passportNumber" },
      { name: "encryptedValue", type: "binData",  required: true,  bian: null,                     note: "QE ciphertext (subType:06). Equality-queryable. Server never sees plaintext." },
      { name: "dekId",          type: "string",   required: true,  bian: null,                     note: "UUID alt-name reference to __keyVault DEK" },
      { name: "algorithm",      type: "string",   required: true,  bian: null,                     note: "Deterministic — enables equality queries. Do not use Random for queryable fields." },
      { name: "writtenAt",      type: "date",     required: true,  bian: null,                     note: "Initial encryption write timestamp" },
      { name: "lastAccessedAt", type: "date",     required: false, bian: null,                     note: "Updated on each authorized decryption read (audit trail)" },
    ],
    indexes: [
      { name: "idx_customer_field_unique", key: "{ customerId: 1, fieldName: 1 }", unique: true },
      { name: "idx_dekId",                 key: "{ dekId: 1 }",                    note: "Used for DEK rotation scope queries and crypto-shred impact analysis" },
      { name: "idx_writtenAt",             key: "{ writtenAt: -1 }" },
    ],
    sampleDocument: {
      customerId: "CUST-FRIDA-001",
      fieldName: "nationalId",
      encryptedValue: { $binary: { base64: "BhPxK3m9qR4TzJ2N+QkL...==", subType: "06" } },
      dekId: "DEK-FRIDA-001",
      algorithm: "Deterministic",
      writtenAt: { $date: "2026-05-06T09:00:00Z" },
      lastAccessedAt: { $date: "2026-05-06T09:00:00Z" },
    },
    designDecisionIds: [],
  },

  keyVaultDek: {
    mongoAlias: "__keyVault",
    description:
      "MongoDB driver key vault — one document per Data Encryption Key (DEK). Managed exclusively via the MongoDB ClientEncryption API. The keyMaterial is wrapped by your KMS master key and is never stored in plaintext. Deleting a document from this collection permanently destroys the ability to decrypt any ciphertext encrypted with that DEK — this is the crypto-shred mechanism.",
    immutable: false,
    bianClassification: {
      sd: "SystemAdministration",
      cr: "KeyVaultRecord",
      bq: "EncryptionKey",
      pattern: "Management",
    },
    fields: [
      { name: "_id",         type: "binData", required: true,  bian: null, note: "UUID (subType:04) generated by MongoDB driver. Never set manually." },
      { name: "keyMaterial", type: "binData", required: true,  bian: null, note: "KMS-wrapped DEK bytes (subType:00). Never decrypt manually — use ClientEncryption API only." },
      { name: "creationDate",type: "date",    required: true,  bian: null, note: "Set by driver at createDataKey() call time" },
      { name: "updateDate",  type: "date",    required: true,  bian: null, note: "Updated on rewrapManyDataKey() operations" },
      { name: "status",      type: "int",     required: true,  bian: null, note: "0 = active, 1 = disabled" },
      { name: "masterKey",   type: "object",  required: true,  bian: null, note: "{ provider, endpoint, keyId } — KMS reference for the wrapping key" },
      { name: "keyAltNames", type: "array",   required: false, bian: null, note: "Alternate name strings — e.g. 'DEK-FRIDA-001'. Sparse unique index. Used by createEncryptedCollection." },
      { name: "version",     type: "long",    required: false, bian: null, note: "Incremented on each rewrap. Used to detect stale key handles." },
    ],
    indexes: [
      { name: "idx_keyAltNames_unique", key: "{ keyAltNames: 1 }", unique: true, sparse: true },
      { name: "idx_status",             key: "{ status: 1 }" },
      { name: "idx_creationDate",       key: "{ creationDate: -1 }" },
    ],
    sampleDocument: {
      _id: { $binary: { base64: "AAECBAUGB...==", subType: "04" } },
      keyMaterial: { $binary: { base64: "Bh7mN2kLpQ8Rz...==", subType: "00" } },
      creationDate: { $date: "2026-05-06T09:00:00Z" },
      updateDate:   { $date: "2026-05-06T09:00:00Z" },
      status: 0,
      masterKey: {
        provider: "kmip",
        endpoint: "vault.leafybank.internal",
        keyId: "master-001",
      },
      keyAltNames: ["DEK-FRIDA-001"],
      version: { $numberLong: "1" },
    },
    designDecisionIds: [],
  },

  cdcResumeTokens: {
    mongoAlias: "cdcResumeTokens",
    description:
      "CDC consumer state — one document per logical consumer per watched collection. Tracks the post-batch resume token (PBRT), consumer status, event lag, and cumulative event count. On reconnect, the consumer passes resumeToken to changeStream({ startAfter: token }) for exactly-once replay. Error code 286 (ChangeStreamHistoryLost) is recorded here when the oplog window expires.",
    immutable: false,
    bianClassification: {
      sd: "FinancialAccounting",
      cr: "FinancialBookingLog",
      bq: "ChangeStreamConsumer",
      pattern: "Management",
    },
    fields: [
      { name: "consumerId",       type: "string",  required: true,  bian: null,                    note: "Logical consumer name — e.g. balance-projection | fraud-pipeline | worm-sink" },
      { name: "collection",       type: "string",  required: true,  bian: null,                    note: "Watched MongoDB collection — e.g. journalEntries" },
      { name: "resumeToken",      type: "object",  required: true,  bian: null,                    note: "Opaque token from last processed event. Pass as-is to startAfter. Never construct manually." },
      { name: "pbrt",             type: "object",  required: false, bian: null,                    note: "Post-batch resume token from last committed batch. More durable than per-event token for high-throughput consumers." },
      { name: "status",           type: "string",  required: true,  bian: null,                    note: "ACTIVE | OFFLINE | ERROR_286 | RECOVERING" },
      { name: "lagMs",            type: "int",     required: false, bian: null,                    note: "Estimated milliseconds behind live oplog head" },
      { name: "eventsProcessed",  type: "long",    required: false, bian: null,                    note: "Cumulative events processed — monotonically increasing" },
      { name: "lastEventAt",      type: "date",    required: false, bian: null,                    note: "clusterTime of last processed change event" },
      { name: "error",            type: "object",  required: false, bian: null,                    note: "{ code, message, at } — populated on ERROR_286. Cleared on successful recovery." },
      { name: "updatedAt",        type: "date",    required: true,  bian: null },
    ],
    indexes: [
      { name: "idx_consumer_collection_unique", key: "{ consumerId: 1, collection: 1 }", unique: true },
      { name: "idx_status",                     key: "{ status: 1 }" },
      { name: "idx_updatedAt",                  key: "{ updatedAt: -1 }" },
    ],
    sampleDocument: {
      consumerId: "fraud-pipeline",
      collection: "journalEntries",
      resumeToken: { _data: "8263E14400000000012B022C0100296E5A1004AB..." },
      pbrt:        { _data: "8263E14400000000012B022C0100296E5A1004AB..." },
      status: "ACTIVE",
      lagMs: 12,
      eventsProcessed: { $numberLong: "58947" },
      lastEventAt: { $date: "2026-05-06T17:59:58Z" },
      error: null,
      updatedAt: { $date: "2026-05-06T17:59:58Z" },
    },
    designDecisionIds: [],
  },

  reconciliationRuns: {
    mongoAlias: "reconciliationRuns",
    description:
      "Reconciliation run records — one document per scheduled or on-demand reconciliation run. Tracks the source-target pair, run type, entry counts, totals, break amount, and duration. Mutable during execution (status: RUNNING); effectively immutable once complete. Period close is blocked while any UNBALANCED run exists.",
    immutable: false,
    bianClassification: {
      sd: "FinancialAccounting",
      cr: "FinancialReconciliation",
      bq: "ReconciliationRun",
      pattern: "Management",
    },
    fields: [
      { name: "_id",                type: "objectId", required: true,  bian: null,                             note: "MongoDB PK" },
      { name: "runId",              type: "string",   required: true,  bian: "ReconciliationRunReference",     note: "e.g. RUN-20260506-001. Indexed unique." },
      { name: "runType",            type: "string",   required: true,  bian: "ReconciliationRunType",          note: "SUB_LEDGER_TO_GL | SUB_LEDGER_TO_SUB_LEDGER | STATEMENT_TO_LEDGER | POSITION_TO_POSITION | BANK_NOSTRO" },
      { name: "periodCode",         type: "string",   required: true,  bian: "FinancialPeriodReference",       note: "ISO year-month e.g. 2026-04" },
      { name: "controlAccountCode", type: "string",   required: false, bian: "ControlAccountReference",       note: "GL account being reconciled. Null for peer-to-peer runs." },
      { name: "sourceCollection",   type: "string",   required: true,  bian: null,                             note: "MongoDB collection name for source side" },
      { name: "targetCollection",   type: "string",   required: true,  bian: null,                             note: "MongoDB collection name for target side" },
      { name: "sourceCount",        type: "int",      required: false, bian: null,                             note: "Number of source entries scanned" },
      { name: "targetCount",        type: "int",      required: false, bian: null,                             note: "Number of target entries scanned" },
      { name: "sourceTotal",        type: "decimal",  required: false, bian: "FinancialBookingAmount",         note: "Σ(source entries)" },
      { name: "targetTotal",        type: "decimal",  required: false, bian: "FinancialBookingAmount",         note: "Σ(target entries)" },
      { name: "breakAmount",        type: "decimal",  required: false, bian: null,                             note: "sourceTotal − targetTotal. Zero iff BALANCED." },
      { name: "currency",           type: "string",   required: true,  bian: "CurrencyCode",                  note: "ISO 4217" },
      { name: "status",             type: "string",   required: true,  bian: "ReconciliationRunStatus",        note: "RUNNING | BALANCED | UNBALANCED | FAILED" },
      { name: "triggeredBy",        type: "string",   required: true,  bian: null,                             note: "SCHEDULED | MANUAL | EVENT" },
      { name: "startedAt",          type: "date",     required: true  },
      { name: "completedAt",        type: "date",     required: false },
      { name: "durationMs",         type: "int",      required: false },
    ],
    indexes: [
      { name: "idx_runId_unique",    key: "{ runId: 1 }",                  unique: true },
      { name: "idx_period_type",     key: "{ periodCode: 1, runType: 1 }" },
      { name: "idx_status",          key: "{ status: 1 }" },
      { name: "idx_control_account", key: "{ controlAccountCode: 1 }",     sparse: true },
      { name: "idx_startedAt",       key: "{ startedAt: -1 }" },
    ],
    sampleDocument: {
      runId: "RUN-20260506-001",
      runType: "SUB_LEDGER_TO_GL",
      periodCode: "2026-04",
      controlAccountCode: "2100",
      sourceCollection: "subLedgerEntries",
      targetCollection: "glAccounts",
      sourceCount: 58947,
      targetCount: 58947,
      sourceTotal: { $numberDecimal: "984723.11" },
      targetTotal: { $numberDecimal: "984722.11" },
      breakAmount: { $numberDecimal: "1.00" },
      currency: "USD",
      status: "BALANCED",
      triggeredBy: "SCHEDULED",
      startedAt:   { $date: "2026-05-06T18:00:00Z" },
      completedAt: { $date: "2026-05-06T18:00:04Z" },
      durationMs: 4120,
    },
    designDecisionIds: [],
  },

  reconciliationExceptions: {
    mongoAlias: "reconciliationExceptions",
    description:
      "Reconciliation exceptions — one document per detected break. Lifecycle: OPEN → INVESTIGATING → RESOLVED | DEFERRED | WRITE_OFF. Links to the parent reconciliationRun and, on resolution, to the correction journal posting. Period close cannot proceed while CRITICAL or HIGH exceptions remain unresolved.",
    immutable: false,
    bianClassification: {
      sd: "FinancialAccounting",
      cr: "FinancialReconciliation",
      bq: "ReconciliationException",
      pattern: "Management",
    },
    fields: [
      { name: "_id",                 type: "objectId", required: true,  bian: null,                               note: "MongoDB PK" },
      { name: "exceptionId",         type: "string",   required: true,  bian: "ReconciliationExceptionReference", note: "e.g. EXC-20260506-001. Indexed unique." },
      { name: "runId",               type: "string",   required: true,  bian: "ReconciliationRunReference",       note: "FK → reconciliationRuns.runId" },
      { name: "exceptionType",       type: "string",   required: true,  bian: "ReconciliationExceptionType",      note: "AMOUNT_MISMATCH | MISSING_ENTRY | DUPLICATE | TIMING_DIFFERENCE" },
      { name: "priority",            type: "string",   required: true,  bian: "ProcessingPriorityLevel",          note: "CRITICAL (2h SLA) | HIGH (8h) | MEDIUM (24h) | LOW (72h)" },
      { name: "status",              type: "string",   required: true,  bian: "ReconciliationExceptionStatus",    note: "OPEN | INVESTIGATING | RESOLVED | DEFERRED | WRITE_OFF" },
      { name: "breakAmount",         type: "decimal",  required: false, bian: null,                               note: "Δ at time of detection" },
      { name: "currency",            type: "string",   required: true,  bian: "CurrencyCode",                     note: "ISO 4217" },
      { name: "controlAccountCode",  type: "string",   required: false, bian: null,                               note: "GL account where break was detected" },
      { name: "relatedEntryId",      type: "string",   required: false, bian: null,                               note: "Source entry ID that caused the break" },
      { name: "slaHours",            type: "int",      required: false, bian: null,                               note: "SLA in hours derived from priority" },
      { name: "slaDeadline",         type: "date",     required: false, bian: null,                               note: "Computed: createdAt + slaHours" },
      { name: "assignedTo",          type: "string",   required: false, bian: null,                               note: "Analyst userId" },
      { name: "notes",               type: "array",    required: false, bian: null,                               note: "Array of { addedBy, addedAt, text } — investigation trail" },
      { name: "correctionJournalId", type: "string",   required: false, bian: null,                               note: "FK → journalEntries.journalId — set on RESOLVED" },
      { name: "createdAt",           type: "date",     required: true  },
      { name: "updatedAt",           type: "date",     required: true  },
      { name: "resolvedAt",          type: "date",     required: false },
    ],
    indexes: [
      { name: "idx_exceptionId_unique", key: "{ exceptionId: 1 }",            unique: true },
      { name: "idx_runId",              key: "{ runId: 1 }" },
      { name: "idx_status_priority",    key: "{ status: 1, priority: 1 }" },
      { name: "idx_sla_deadline",       key: "{ slaDeadline: 1 }",            sparse: true },
      { name: "idx_createdAt",          key: "{ createdAt: -1 }" },
    ],
    sampleDocument: {
      exceptionId: "EXC-20260506-001",
      runId: "RUN-20260506-001",
      exceptionType: "AMOUNT_MISMATCH",
      priority: "HIGH",
      status: "RESOLVED",
      breakAmount: { $numberDecimal: "1.00" },
      currency: "USD",
      controlAccountCode: "2100",
      relatedEntryId: "SL-20260430-047823",
      slaHours: 8,
      slaDeadline: { $date: "2026-05-07T02:00:05Z" },
      assignedTo: "analyst.frida",
      notes: [
        { addedBy: "system",        addedAt: { $date: "2026-05-06T18:00:05Z" }, text: "Auto-detected: Σ(subLedgerEntries) − Σ(GL 2100) = $1.00." },
        { addedBy: "analyst.frida", addedAt: { $date: "2026-05-06T18:31:08Z" }, text: "Root cause: rounding loss on FX convert in SL-20260430-047823." },
      ],
      correctionJournalId: "JNL-20260506-CORR-001",
      createdAt:   { $date: "2026-05-06T18:00:05Z" },
      updatedAt:   { $date: "2026-05-06T18:32:01Z" },
      resolvedAt:  { $date: "2026-05-06T18:32:01Z" },
    },
    designDecisionIds: [],
  },

};
